-- Test fixture data generated from XML
-- Disable foreign key checks for loading
SET FOREIGN_KEY_CHECKS=0;

-- Clear existing data
DELETE FROM `tags_modules_items`;
DELETE FROM `tags`;
DELETE FROM `search_word_module`;
DELETE FROM `search_words`;
DELETE FROM `search_display`;
DELETE FROM `history`;
DELETE FROM `frontend_message`;
DELETE FROM `item_rights`;
DELETE FROM `project_role_user_permissions`;
DELETE FROM `project_module_permissions`;
DELETE FROM `role_module_permissions`;
DELETE FROM `role`;
DELETE FROM `module_tab_relation`;
DELETE FROM `tab`;
DELETE FROM `module_instance`;
DELETE FROM `groups_user_relation`;
DELETE FROM `groups`;
DELETE FROM `setting`;
DELETE FROM `configuration`;
DELETE FROM `user_contract_relation`;
DELETE FROM `contract`;
DELETE FROM `timecard`;
DELETE FROM `user_proxy`;
DELETE FROM `user`;
DELETE FROM `calendar2_user_relation`;
DELETE FROM `calendar2_excluded_dates`;
DELETE FROM `calendar2`;
DELETE FROM `hmabtm_test_project_relation`;
DELETE FROM `hmabtm_test`;
DELETE FROM `project`;
DELETE FROM `module`;
DELETE FROM `database_manager`;

-- Insert fixture data

-- From Phprojekt/data.xml
REPLACE INTO `project` (`id`, `path`, `title`, `notes`, `owner_id`, `start_date`, `priority`, `current_status`) VALUES (1, '/', 'PHProjekt', NULL, 1, '2007-12-01', 1, 3);
REPLACE INTO `project` (`id`, `path`, `title`, `notes`, `owner_id`, `project_id`, `start_date`, `priority`, `current_status`) VALUES (2, '/1/', 'Test Project', NULL, 1, 1, '2007-12-01', 1, 3);
REPLACE INTO `project` (`id`, `path`, `title`, `notes`, `owner_id`, `project_id`, `start_date`, `priority`, `current_status`) VALUES (5, '/1/2/', 'Sub Project', NULL, 1, 2, '1987-03-22', 1, 3);
REPLACE INTO `project` (`id`, `path`, `title`, `notes`, `owner_id`, `project_id`, `start_date`, `priority`, `current_status`) VALUES (6, '/1/2/5/', 'Sub Sub Project 1', NULL, 1, 5, '2007-12-01', 1, 3);
REPLACE INTO `project` (`id`, `path`, `title`, `notes`, `owner_id`, `project_id`, `start_date`, `priority`, `current_status`) VALUES (7, '/1/2/5/', 'Sub Sub Project 2', NULL, 1, 5, '2007-12-01', 1, 3);
REPLACE INTO `user` (`id`, `username`, `firstname`, `lastname`, `status`, `admin`) VALUES (1, 'Test', 'Max', 'Mustermann', 'A', 1);
REPLACE INTO `user` (`id`, `username`, `firstname`, `lastname`, `status`, `admin`) VALUES (2, 'Marie', 'Luise Marie', NULL, 'A', 0);
REPLACE INTO `module` (`id`, `name`, `label`, `save_type`, `version`, `active`) VALUES (1, 'Project', 'Project', 0, '6.1.4', 1);
REPLACE INTO `project_module_permissions` (`module_id`, `project_id`) VALUES (1, 1);
REPLACE INTO `project_module_permissions` (`module_id`, `project_id`) VALUES (1, 2);
REPLACE INTO `project_role_user_permissions` (`project_id`, `user_id`, `role_id`) VALUES (2, 1, 1);
REPLACE INTO `project_role_user_permissions` (`project_id`, `user_id`, `role_id`) VALUES (1, 1, 1);
REPLACE INTO `item_rights` (`module_id`, `item_id`, `user_id`, `access`) VALUES (1, 1, 1, 255);
REPLACE INTO `item_rights` (`module_id`, `item_id`, `user_id`, `access`) VALUES (1, 2, 1, 255);
REPLACE INTO `item_rights` (`module_id`, `item_id`, `user_id`, `access`) VALUES (1, 5, 1, 255);
REPLACE INTO `item_rights` (`module_id`, `item_id`, `user_id`, `access`) VALUES (1, 6, 1, 255);
REPLACE INTO `item_rights` (`module_id`, `item_id`, `user_id`, `access`) VALUES (1, 7, 1, 255);
REPLACE INTO `item_rights` (`module_id`, `item_id`, `user_id`, `access`) VALUES (1, 2, 3, 255);
REPLACE INTO `role` (`id`, `name`) VALUES (1, 'Admin');
REPLACE INTO `role_module_permissions` (`role_id`, `module_id`, `access`) VALUES (1, 1, 139);
REPLACE INTO `groups` (`id`, `name`) VALUES (1, 'Group 1');
REPLACE INTO `groups` (`id`, `name`) VALUES (2, 'Group 2');
REPLACE INTO `groups_user_relation` (`user_id`, `groups_id`) VALUES (1, 1);
REPLACE INTO `groups_user_relation` (`user_id`, `groups_id`) VALUES (2, 1);
REPLACE INTO `groups_user_relation` (`user_id`, `groups_id`) VALUES (1, 2);
REPLACE INTO `database_manager` (`table_name`, `table_field`, `form_tab`, `form_label`, `form_type`, `form_position`, `form_columns`, `form_regexp`, `form_range`, `default_value`, `list_position`, `list_align`, `list_use_filter`, `alt_position`, `status`, `is_integer`, `is_required`, `is_unique`) VALUES ('Project', 'title', 1, 'Title', 'text', 1, 1, NULL, NULL, NULL, 1, 'left', 1, 2, 1, 0, 1, 0);
REPLACE INTO `database_manager` (`table_name`, `table_field`, `form_tab`, `form_label`, `form_type`, `form_position`, `form_columns`, `form_regexp`, `form_range`, `default_value`, `list_position`, `list_align`, `list_use_filter`, `alt_position`, `status`, `is_integer`, `is_required`, `is_unique`) VALUES ('Project', 'notes', 1, 'Notes', 'textarea', 2, 1, NULL, NULL, NULL, 0, 'left', 1, 0, 1, 0, 0, 0);
REPLACE INTO `database_manager` (`table_name`, `table_field`, `form_tab`, `form_label`, `form_type`, `form_position`, `form_columns`, `form_regexp`, `form_range`, `default_value`, `list_position`, `list_align`, `list_use_filter`, `alt_position`, `status`, `is_integer`, `is_required`, `is_unique`) VALUES ('Project', 'project_id', 1, 'Parent', 'selectValues', 3, 1, NULL, 'Project#id#title', NULL, 0, NULL, 1, 0, 1, 1, 1, 0);
REPLACE INTO `database_manager` (`table_name`, `table_field`, `form_tab`, `form_label`, `form_type`, `form_position`, `form_columns`, `form_regexp`, `form_range`, `default_value`, `list_position`, `list_align`, `list_use_filter`, `alt_position`, `status`, `is_integer`, `is_required`, `is_unique`) VALUES ('Project', 'start_date', 1, 'Start date', 'date', 4, 1, NULL, NULL, NULL, 2, 'left', 1, 2, 1, 0, 0, 0);
REPLACE INTO `database_manager` (`table_name`, `table_field`, `form_tab`, `form_label`, `form_type`, `form_position`, `form_columns`, `form_regexp`, `form_range`, `default_value`, `list_position`, `list_align`, `list_use_filter`, `alt_position`, `status`, `is_integer`, `is_required`, `is_unique`) VALUES ('Project', 'end_date', 1, 'End date', 'date', 5, 1, NULL, NULL, NULL, 3, 'left', 1, 2, 1, 0, 0, 0);
REPLACE INTO `database_manager` (`table_name`, `table_field`, `form_tab`, `form_label`, `form_type`, `form_position`, `form_columns`, `form_regexp`, `form_range`, `default_value`, `list_position`, `list_align`, `list_use_filter`, `alt_position`, `status`, `is_integer`, `is_required`, `is_unique`) VALUES ('Project', 'priority', 1, 'Priority', 'rating', 6, 1, NULL, 10, 5, 5, 'center', 1, 5, 1, 1, 0, 0);
REPLACE INTO `database_manager` (`table_name`, `table_field`, `form_tab`, `form_label`, `form_type`, `form_position`, `form_columns`, `form_regexp`, `form_range`, `default_value`, `list_position`, `list_align`, `list_use_filter`, `alt_position`, `status`, `is_integer`, `is_required`, `is_unique`) VALUES ('Project', 'current_status', 1, 'Current status', 'selectValues', 7, 1, NULL, '1#Offered|2#Ordered|3#Working|4#Ended|5#Stopped|6#Re-Opened|7#Waiting', NULL, 6, 'left', 1, 2, 1, 1, 0, 0);
REPLACE INTO `database_manager` (`table_name`, `table_field`, `form_tab`, `form_label`, `form_type`, `form_position`, `form_columns`, `form_regexp`, `form_range`, `default_value`, `list_position`, `list_align`, `list_use_filter`, `alt_position`, `status`, `is_integer`, `is_required`, `is_unique`) VALUES ('Project', 'complete_percent', 1, 'Complete percent', 'percentage', 8, 1, NULL, NULL, NULL, 7, 'left', 1, 2, 1, 0, 0, 0);
REPLACE INTO `database_manager` (`table_name`, `table_field`, `form_tab`, `form_label`, `form_type`, `form_position`, `form_columns`, `form_regexp`, `form_range`, `default_value`, `list_position`, `list_align`, `list_use_filter`, `alt_position`, `status`, `is_integer`, `is_required`, `is_unique`) VALUES ('Project', 'budget', 1, 'Budget', 'percentage', 9, 1, NULL, NULL, NULL, 0, 'left', 1, 2, 1, 0, 0, 0);
REPLACE INTO `module_instance` (`id`, `project_id`, `module`, `name`) VALUES (1, 2, 'Fnord', 'Developer Tasks');
REPLACE INTO `module_instance` (`id`, `project_id`, `module`, `name`) VALUES (2, 2, 'Fnord', 'Project Tasks');
REPLACE INTO `module_instance` (`id`, `project_id`, `module`, `name`) VALUES (3, 1, 'plom', 'Project Tasks plom');
REPLACE INTO `tags` (`id`, `word`) VALUES (1, 'this');
REPLACE INTO `tags` (`id`, `word`) VALUES (2, 'tag');
REPLACE INTO `tags` (`id`, `word`) VALUES (3, 'blafoo');
REPLACE INTO `tags` (`id`, `word`) VALUES (4, 'blaboo');
REPLACE INTO `tags` (`id`, `word`) VALUES (5, 'blawoo');
REPLACE INTO `tags_modules_items` (`tag_id`, `module_id`, `item_id`) VALUES (1, 1, 1);
REPLACE INTO `tags_modules_items` (`tag_id`, `module_id`, `item_id`) VALUES (2, 20, 1);
REPLACE INTO `tags_modules_items` (`tag_id`, `module_id`, `item_id`) VALUES (3, 1, 2);
REPLACE INTO `tags_modules_items` (`tag_id`, `module_id`, `item_id`) VALUES (3, 1, 5);
REPLACE INTO `tags_modules_items` (`tag_id`, `module_id`, `item_id`) VALUES (4, 1, 6);
REPLACE INTO `tags_modules_items` (`tag_id`, `module_id`, `item_id`) VALUES (5, 1, 6);
REPLACE INTO `search_display` (`module_id`, `item_id`, `project_id`, `first_display`) VALUES (1, 1, 1, 'Hallo Welt');
REPLACE INTO `search_display` (`module_id`, `item_id`, `project_id`, `first_display`) VALUES (1, 6, 5, 'BWV 810 - II. Allemande');
REPLACE INTO `search_words` (`id`, `word`, `count`) VALUES (1, 'Karlsruhe', 1);
REPLACE INTO `search_word_module` (`word_id`, `item_id`, `module_id`) VALUES (1, 1, 1);
REPLACE INTO `history` (`id`, `module_id`, `user_id`, `item_id`, `field`, `old_value`, `new_value`, `action`, `datetime`) VALUES (1, 1, 1, 1, 'title', 'TEST', 'EDITED TEST', 'edit', '2001-02-23 23:23:42');
REPLACE INTO `tab` (`id`, `label`) VALUES (1, 'Basic Data');
REPLACE INTO `module_tab_relation` (`tab_id`, `module_id`) VALUES (1, 1);
REPLACE INTO `setting` (`user_id`, `module_id`, `key_value`, `value`, `identifier`) VALUES (1, 4, 'favorites', 'a:2:{i:0;i:1;i:1;i:2;}', 'Timecard');
REPLACE INTO `setting` (`user_id`, `module_id`, `key_value`, `value`, `identifier`) VALUES (1, 0, 'language', 'en', 'core');
REPLACE INTO `setting` (`user_id`, `module_id`, `key_value`, `value`, `identifier`) VALUES (1, 0, 'loginlogout', 0, 'notification');
REPLACE INTO `setting` (`user_id`, `module_id`, `key_value`, `value`, `identifier`) VALUES (1, 0, 'datarecords', 1, 'notification');
REPLACE INTO `setting` (`user_id`, `module_id`, `key_value`, `value`, `identifier`) VALUES (1, 0, 'alerts', 1, 'notification');
REPLACE INTO `setting` (`user_id`, `module_id`, `key_value`, `value`, `identifier`) VALUES (1, 0, 'password', '156c3239dbfa5c5222b51514e9d12948', 'Core');

-- From ActiveRecord/data.xml
REPLACE INTO `project` (`id`, `path`, `title`, `notes`, `owner_id`, `start_date`, `priority`, `current_status`) VALUES (1, '/', 'PHProjekt', NULL, 1, '2007-12-01', 1, 3);
REPLACE INTO `project` (`id`, `path`, `title`, `notes`, `owner_id`, `project_id`, `start_date`, `priority`, `current_status`) VALUES (2, '/1/', 'Test Project', NULL, 1, 1, '2007-12-01', 1, 3);
REPLACE INTO `project` (`id`, `path`, `title`, `notes`, `owner_id`, `project_id`, `start_date`, `priority`, `current_status`) VALUES (5, '/1/2/', 'Sub Project', NULL, 1, 2, '1987-03-22', 1, 3);
REPLACE INTO `project` (`id`, `path`, `title`, `notes`, `owner_id`, `project_id`, `start_date`, `priority`, `current_status`) VALUES (6, '/1/2/5/', 'Sub Sub Project 1', NULL, 1, 5, '2007-12-01', 1, 3);
REPLACE INTO `project` (`id`, `path`, `title`, `notes`, `owner_id`, `project_id`, `start_date`, `priority`, `current_status`) VALUES (7, '/1/2/5/', 'Sub Sub Project 2', NULL, 1, 5, '2007-12-01', 1, 3);
REPLACE INTO `user` (`id`, `username`, `firstname`, `lastname`, `status`, `admin`) VALUES (1, 'Test', 'Max', 'Mustermann', 'A', 1);
REPLACE INTO `user` (`id`, `username`, `firstname`, `lastname`, `status`, `admin`) VALUES (2, 'Marie', 'Luise Marie', NULL, 'A', 0);
REPLACE INTO `module` (`id`, `name`, `label`, `save_type`, `version`, `active`) VALUES (1, 'Project', 'Project', 0, '6.1.0-dev', 1);
REPLACE INTO `project_module_permissions` (`module_id`, `project_id`) VALUES (1, 1);
REPLACE INTO `project_module_permissions` (`module_id`, `project_id`) VALUES (1, 2);
REPLACE INTO `project_role_user_permissions` (`project_id`, `user_id`, `role_id`) VALUES (2, 1, 1);
REPLACE INTO `project_role_user_permissions` (`project_id`, `user_id`, `role_id`) VALUES (1, 1, 1);
REPLACE INTO `item_rights` (`module_id`, `item_id`, `user_id`, `access`) VALUES (1, 1, 1, 255);
REPLACE INTO `item_rights` (`module_id`, `item_id`, `user_id`, `access`) VALUES (1, 2, 1, 255);
REPLACE INTO `item_rights` (`module_id`, `item_id`, `user_id`, `access`) VALUES (1, 5, 1, 255);
REPLACE INTO `item_rights` (`module_id`, `item_id`, `user_id`, `access`) VALUES (1, 6, 1, 255);
REPLACE INTO `item_rights` (`module_id`, `item_id`, `user_id`, `access`) VALUES (1, 7, 1, 255);
REPLACE INTO `item_rights` (`module_id`, `item_id`, `user_id`, `access`) VALUES (1, 2, 3, 255);
REPLACE INTO `role` (`id`, `name`) VALUES (1, 'Admin');
REPLACE INTO `role_module_permissions` (`role_id`, `module_id`, `access`) VALUES (1, 1, 139);
REPLACE INTO `groups` (`id`, `name`) VALUES (1, 'Group 1');
REPLACE INTO `groups` (`id`, `name`) VALUES (2, 'Group 2');
REPLACE INTO `groups_user_relation` (`user_id`, `groups_id`) VALUES (1, 1);
REPLACE INTO `groups_user_relation` (`user_id`, `groups_id`) VALUES (2, 1);
REPLACE INTO `groups_user_relation` (`user_id`, `groups_id`) VALUES (1, 2);
REPLACE INTO `database_manager` (`table_name`, `table_field`, `form_tab`, `form_label`, `form_type`, `form_position`, `form_columns`, `form_regexp`, `form_range`, `default_value`, `list_position`, `list_align`, `list_use_filter`, `alt_position`, `status`, `is_integer`, `is_required`, `is_unique`) VALUES ('Project', 'title', 1, 'Title', 'text', 1, 1, NULL, NULL, NULL, 1, 'left', 1, 2, 1, 0, 1, 0);
REPLACE INTO `database_manager` (`table_name`, `table_field`, `form_tab`, `form_label`, `form_type`, `form_position`, `form_columns`, `form_regexp`, `form_range`, `default_value`, `list_position`, `list_align`, `list_use_filter`, `alt_position`, `status`, `is_integer`, `is_required`, `is_unique`) VALUES ('Project', 'notes', 1, 'Notes', 'textarea', 2, 1, NULL, NULL, NULL, 0, 'left', 1, 0, 1, 0, 0, 0);
REPLACE INTO `database_manager` (`table_name`, `table_field`, `form_tab`, `form_label`, `form_type`, `form_position`, `form_columns`, `form_regexp`, `form_range`, `default_value`, `list_position`, `list_align`, `list_use_filter`, `alt_position`, `status`, `is_integer`, `is_required`, `is_unique`) VALUES ('Project', 'project_id', 1, 'Parent', 'selectValues', 3, 1, NULL, 'Project#id#title', NULL, 0, NULL, 1, 0, 1, 1, 1, 0);
REPLACE INTO `database_manager` (`table_name`, `table_field`, `form_tab`, `form_label`, `form_type`, `form_position`, `form_columns`, `form_regexp`, `form_range`, `default_value`, `list_position`, `list_align`, `list_use_filter`, `alt_position`, `status`, `is_integer`, `is_required`, `is_unique`) VALUES ('Project', 'start_date', 1, 'Start date', 'date', 4, 1, NULL, NULL, NULL, 2, 'left', 1, 2, 1, 0, 0, 0);
REPLACE INTO `database_manager` (`table_name`, `table_field`, `form_tab`, `form_label`, `form_type`, `form_position`, `form_columns`, `form_regexp`, `form_range`, `default_value`, `list_position`, `list_align`, `list_use_filter`, `alt_position`, `status`, `is_integer`, `is_required`, `is_unique`) VALUES ('Project', 'end_date', 1, 'End date', 'date', 5, 1, NULL, NULL, NULL, 3, 'left', 1, 2, 1, 0, 0, 0);
REPLACE INTO `database_manager` (`table_name`, `table_field`, `form_tab`, `form_label`, `form_type`, `form_position`, `form_columns`, `form_regexp`, `form_range`, `default_value`, `list_position`, `list_align`, `list_use_filter`, `alt_position`, `status`, `is_integer`, `is_required`, `is_unique`) VALUES ('Project', 'priority', 1, 'Priority', 'rating', 6, 1, NULL, 10, 5, 5, 'center', 1, 5, 1, 1, 0, 0);
REPLACE INTO `database_manager` (`table_name`, `table_field`, `form_tab`, `form_label`, `form_type`, `form_position`, `form_columns`, `form_regexp`, `form_range`, `default_value`, `list_position`, `list_align`, `list_use_filter`, `alt_position`, `status`, `is_integer`, `is_required`, `is_unique`) VALUES ('Project', 'current_status', 1, 'Current status', 'selectValues', 7, 1, NULL, '1#Offered|2#Ordered|3#Working|4#Ended|5#Stopped|6#Re-Opened|7#Waiting', NULL, 5, 'left', 1, 2, 1, 1, 0, 0);
REPLACE INTO `database_manager` (`table_name`, `table_field`, `form_tab`, `form_label`, `form_type`, `form_position`, `form_columns`, `form_regexp`, `form_range`, `default_value`, `list_position`, `list_align`, `list_use_filter`, `alt_position`, `status`, `is_integer`, `is_required`, `is_unique`) VALUES ('Project', 'complete_percent', 1, 'Complete percent', 'percentage', 8, 1, NULL, NULL, NULL, 6, 'left', 1, 2, 1, 0, 0, 0);
REPLACE INTO `database_manager` (`table_name`, `table_field`, `form_tab`, `form_label`, `form_type`, `form_position`, `form_columns`, `form_regexp`, `form_range`, `default_value`, `list_position`, `list_align`, `list_use_filter`, `alt_position`, `status`, `is_integer`, `is_required`, `is_unique`) VALUES ('Project', 'budget', 1, 'Budget', 'percentage', 9, 1, NULL, NULL, NULL, 0, 'left', 1, 2, 1, 0, 0, 0);
REPLACE INTO `module_instance` (`id`, `project_id`, `module`, `name`) VALUES (1, 2, 'Fnord', 'Developer Tasks');
REPLACE INTO `module_instance` (`id`, `project_id`, `module`, `name`) VALUES (2, 2, 'Fnord', 'Project Tasks');
REPLACE INTO `module_instance` (`id`, `project_id`, `module`, `name`) VALUES (3, 1, 'plom', 'Project Tasks plom');
REPLACE INTO `hmabtm_test` (`id`) VALUES (1);
REPLACE INTO `hmabtm_test` (`id`) VALUES (2);
REPLACE INTO `hmabtm_test_project_relation` (`project_id`, `hmabtm_test_id`) VALUES (2, 1);
REPLACE INTO `hmabtm_test_project_relation` (`project_id`, `hmabtm_test_id`) VALUES (6, 1);
REPLACE INTO `tags` (`id`, `word`) VALUES (1, 'this');
REPLACE INTO `tags` (`id`, `word`) VALUES (2, 'tag');
REPLACE INTO `search_display` (`module_id`, `item_id`, `project_id`, `first_display`) VALUES (1, 1, 1, 'Hallo Welt');
REPLACE INTO `search_display` (`module_id`, `item_id`, `project_id`, `first_display`) VALUES (1, 6, 5, 'BWV 810 - II. Allemande');
REPLACE INTO `search_words` (`id`, `word`, `count`) VALUES (1, 'Karlsruhe', 1);
REPLACE INTO `search_word_module` (`word_id`, `item_id`, `module_id`) VALUES (1, 1, 1);
REPLACE INTO `history` (`id`, `module_id`, `user_id`, `item_id`, `field`, `old_value`, `new_value`, `action`, `datetime`) VALUES (1, 1, 1, 1, 'title', 'TEST', 'EDITED TEST', 'edit', '2001-02-23 23:23:42');
REPLACE INTO `tab` (`id`, `label`) VALUES (1, 'Basic Data');
REPLACE INTO `module_tab_relation` (`tab_id`, `module_id`) VALUES (1, 1);
REPLACE INTO `setting` (`user_id`, `module_id`, `key_value`, `value`, `identifier`) VALUES (1, 4, 'favorites', 'a:2:{i:0;i:1;i:1;i:2;}', 'Timecard');
REPLACE INTO `setting` (`user_id`, `module_id`, `key_value`, `value`, `identifier`) VALUES (1, 0, 'language', 'en', 'core');
REPLACE INTO `setting` (`user_id`, `module_id`, `key_value`, `value`, `identifier`) VALUES (1, 0, 'loginlogout', 0, 'notification');
REPLACE INTO `setting` (`user_id`, `module_id`, `key_value`, `value`, `identifier`) VALUES (1, 0, 'datarecords', 1, 'notification');
REPLACE INTO `setting` (`user_id`, `module_id`, `key_value`, `value`, `identifier`) VALUES (1, 0, 'alerts', 1, 'notification');
REPLACE INTO `setting` (`user_id`, `module_id`, `key_value`, `value`, `identifier`) VALUES (1, 0, 'password', '156c3239dbfa5c5222b51514e9d12948', 'Core');

-- From Default/data.xml
REPLACE INTO `project` (`id`, `path`, `title`, `notes`, `owner_id`, `start_date`, `priority`, `current_status`) VALUES (1, '/', 'Invisible Root', NULL, 1, '2007-12-01', 1, 3);
REPLACE INTO `project` (`id`, `path`, `title`, `notes`, `owner_id`, `start_date`, `priority`, `current_status`, `project_id`) VALUES (2, '/1/', 'Project 1', NULL, 1, '2007-12-01', 1, 3, 1);
REPLACE INTO `project` (`id`, `path`, `title`, `notes`, `owner_id`, `start_date`, `priority`, `current_status`, `project_id`) VALUES (3, '/1/', 'test', NULL, 1, '2007-12-01', 1, 3, 1);
REPLACE INTO `project` (`id`, `path`, `title`, `notes`, `owner_id`, `start_date`, `priority`, `current_status`, `project_id`) VALUES (4, '/1/3/', 'other test', NULL, 1, '2007-12-01', 1, 3, 3);
REPLACE INTO `user` (`id`, `username`, `firstname`, `lastname`, `status`, `admin`) VALUES (1, 'David', 'Max', 'Mustermann', 'A', 1);
REPLACE INTO `module` (`id`, `name`, `label`, `save_type`, `version`, `active`) VALUES (1, 'Project', 'Project', 0, '6.3.0', 1);
REPLACE INTO `module` (`id`, `name`, `label`, `save_type`, `version`, `active`) VALUES (3, 'Calendar2', 'Calendar', 1, '6.1.0-beta1', 1);
REPLACE INTO `module` (`id`, `name`, `label`, `save_type`, `version`, `active`) VALUES (4, 'Timecard', 'Timecard', 1, '6.3.0', 1);
REPLACE INTO `project_module_permissions` (`module_id`, `project_id`) VALUES (1, 1);
REPLACE INTO `project_module_permissions` (`module_id`, `project_id`) VALUES (2, 1);
REPLACE INTO `project_module_permissions` (`module_id`, `project_id`) VALUES (3, 1);
REPLACE INTO `project_role_user_permissions` (`project_id`, `user_id`, `role_id`) VALUES (2, 1, 1);
REPLACE INTO `project_role_user_permissions` (`project_id`, `user_id`, `role_id`) VALUES (1, 1, 1);
REPLACE INTO `item_rights` (`module_id`, `item_id`, `user_id`, `access`) VALUES (1, 1, 1, 255);
REPLACE INTO `item_rights` (`module_id`, `item_id`, `user_id`, `access`) VALUES (1, 2, 1, 255);
REPLACE INTO `item_rights` (`module_id`, `item_id`, `user_id`, `access`) VALUES (1, 3, 1, 255);
REPLACE INTO `role` (`id`, `name`) VALUES (1, 'Admin');
REPLACE INTO `role_module_permissions` (`role_id`, `module_id`, `access`) VALUES (1, 1, 139);
REPLACE INTO `role_module_permissions` (`role_id`, `module_id`, `access`) VALUES (1, 2, 139);
REPLACE INTO `role_module_permissions` (`role_id`, `module_id`, `access`) VALUES (1, 3, 139);
REPLACE INTO `database_manager` (`table_name`, `table_field`, `form_tab`, `form_label`, `form_type`, `form_position`, `form_columns`, `form_regexp`, `form_range`, `default_value`, `list_position`, `list_align`, `list_use_filter`, `alt_position`, `status`, `is_integer`, `is_required`, `is_unique`) VALUES ('Project', 'title', 1, 'Title', 'text', 1, 1, NULL, NULL, NULL, 1, 'left', 1, 2, 1, 0, 1, 0);
REPLACE INTO `tags` (`id`, `word`) VALUES (1, 'this');
REPLACE INTO `tags` (`id`, `word`) VALUES (2, 'that');
REPLACE INTO `tags` (`id`, `word`) VALUES (3, 'fake');
REPLACE INTO `tags_modules_items` (`tag_id`, `module_id`, `item_id`) VALUES (1, 1, 2);
REPLACE INTO `tags_modules_items` (`tag_id`, `module_id`, `item_id`) VALUES (3, 1, 2);
REPLACE INTO `search_display` (`module_id`, `item_id`, `first_display`, `project_id`) VALUES (1, 1, 'test', 1);
REPLACE INTO `search_words` (`id`, `word`, `count`) VALUES (1, 'note', 1);
REPLACE INTO `search_word_module` (`item_id`, `module_id`, `word_id`) VALUES (1, 1, 1);
REPLACE INTO `setting` (`user_id`, `module_id`, `key_value`, `value`, `identifier`) VALUES (1, 0, 'password', '156c3239dbfa5c5222b51514e9d12948', 'core');

-- From Timecard/data.xml
REPLACE INTO `timecard` (`id`, `owner_id`, `start_datetime`, `end_time`, `minutes`, `project_id`, `notes`, `module_id`, `item_id`, `uri`, `uid`) VALUES (7, 1, '2009-05-17 9:00:00', '13:00:00', 240, 1, 'My note', 2, 1, 'someuri@testing', 'someuid');
REPLACE INTO `timecard` (`id`, `owner_id`, `start_datetime`, `end_time`, `minutes`, `project_id`, `notes`, `module_id`, `item_id`, `uri`, `uid`) VALUES (8, 1, '2009-05-17 14:00:00', '18:00:00', 120, 1, 'My note', 2, 1, 'otheruri@testing', 'otheruid');
REPLACE INTO `timecard` (`id`, `owner_id`, `start_datetime`, `project_id`, `notes`, `module_id`, `item_id`, `uri`, `uid`) VALUES (9, 1, '2009-07-03 10:00:00', 1, 'My note', 2, 1, 'onemore@testing', 'onemore');
REPLACE INTO `contract` (`id`, `name`, `hours_per_week`) VALUES (1, 'Standard', 40);
REPLACE INTO `user_contract_relation` (`id`, `user_id`, `contract_id`, `start`) VALUES (1, 1, 1, '2009-05-01');

-- From User/data.xml
REPLACE INTO `user` (`id`, `username`, `firstname`, `lastname`, `status`, `admin`) VALUES (2, 'Marie', 'Luise Marie', NULL, 'A', 0);

-- Re-enable foreign key checks
SET FOREIGN_KEY_CHECKS=1;
